# Generated by Django 4.0 on 2022-04-18 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_header',
            name='end_validity',
            field=models.DateField(default=datetime.date(2022, 5, 18), verbose_name='Fin validez'),
        ),
        migrations.AlterField(
            model_name='credit_pos',
            name='end_validity',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 11, 0, 32, 443377), verbose_name='Fin validez'),
        ),
    ]
