# Generated by Django 4.0 on 2022-04-18 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_credit_header_end_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_pos',
            name='end_validity',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 11, 1, 2, 585577), verbose_name='Fin validez'),
        ),
    ]
