# Generated by Django 4.0 on 2022-04-18 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_credit_pos_end_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_header',
            name='status',
            field=models.CharField(choices=[('AC', 'Activo'), ('FI', 'Finalizado'), ('CA', 'Cancelado')], default='AC', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='credit_pos',
            name='end_validity',
            field=models.DateField(default=datetime.datetime(2022, 5, 18, 12, 14, 38, 789025), verbose_name='Fin validez'),
        ),
    ]
