# Generated by Django 4.0 on 2022-04-19 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_credit_header_status_alter_credit_pos_end_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_header',
            name='begin_validity',
            field=models.DateField(default=datetime.date(2022, 4, 19), verbose_name='Inicio validez'),
        ),
        migrations.AlterField(
            model_name='credit_header',
            name='end_validity',
            field=models.DateField(default=datetime.date(2022, 5, 19), verbose_name='Fin validez'),
        ),
        migrations.AlterField(
            model_name='credit_pos',
            name='begin_validity',
            field=models.DateField(default=datetime.date(2022, 4, 19), verbose_name='Inicio validez'),
        ),
        migrations.AlterField(
            model_name='credit_pos',
            name='end_validity',
            field=models.DateField(default=datetime.datetime(2022, 5, 19, 13, 47, 27, 91407), verbose_name='Fin validez'),
        ),
    ]
