# Generated by Django 4.0 on 2022-04-19 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_alter_credit_pos_end_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_pos',
            name='end_validity',
            field=models.DateField(default=datetime.datetime(2022, 5, 19, 15, 8, 37, 32350), verbose_name='Fin validez'),
        ),
    ]
