# Generated by Django 4.0 on 2022-05-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_alter_credit_header_status_alter_credit_pos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_header',
            name='status',
            field=models.CharField(choices=[('AC', 'Activo'), ('FI', 'Finalizado')], default='AC', max_length=2, verbose_name='Status'),
        ),
    ]
