# Generated by Django 4.0 on 2022-05-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0081_alter_location_created_at_alter_pool_created_at'),
        ('credits', '0011_alter_credit_header_begin_validity_and_more'),
        ('members', '0081_alter_member_created_at'),
        ('planning', '0014_alter_calendar_day_alter_calendar_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning.calendar')),
                ('credit_header', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='credits.credit_header')),
                ('credit_pos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='credits.credit_pos')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.member')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.pool')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning.slot')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
