# Generated by Django 4.0 on 2022-05-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_alter_credit_header_status_alter_credit_pos_status'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='credit_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='credits.credit_header'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='credit_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='credits.credit_pos'),
        ),
    ]
