# Generated by Django 4.0 on 2022-04-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Posicion'),
            preserve_default=False,
        ),
    ]
