# Generated by Django 4.0 on 2022-04-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='admin',
            field=models.BooleanField(blank=True, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='application',
            name='member',
            field=models.BooleanField(blank=True, verbose_name='Miembro'),
        ),
        migrations.AlterField(
            model_name='application',
            name='staff',
            field=models.BooleanField(blank=True, verbose_name='Empleado'),
        ),
    ]
