# Generated by Django 4.0 on 2021-12-08 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Empleado')),
                ('doc_num', models.CharField(max_length=10, unique=True, verbose_name='N° Documento')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('sex', models.CharField(max_length=1, verbose_name='Sexo')),
                ('job', models.CharField(choices=[('RE', 'Recepcionista'), ('AD', 'Administrador')], default='RE', max_length=2, verbose_name='Trabajo')),
                ('hire_date', models.DateField(null=True, verbose_name='Fecha contratación')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 8, 17, 26, 21, 678859))),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_created_by', to='users.user')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
