# Generated by Django 4.0 on 2022-04-19 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0065_alter_location_created_at_alter_pool_created_at'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_level',
            name='level',
            field=models.IntegerField(default=1, verbose_name='nivel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='courses',
            field=models.ManyToManyField(related_name='cursos', to='catalog.Course', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='services',
            field=models.ManyToManyField(related_name='Servicios', to='catalog.Service', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='course_level',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course', verbose_name='Curso'),
        ),
    ]
