# Generated by Django 4.0 on 2022-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_course_level_level_alter_catalog_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='catalog.Course', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='services',
            field=models.ManyToManyField(related_name='services', to='catalog.Service', verbose_name='Servicios'),
        ),
    ]
