# Generated by Django 4.0 on 2022-04-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0068_alter_location_created_at_alter_pool_created_at'),
        ('catalog', '0004_service_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', unique=True, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='course_level',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='catalog.course', verbose_name='Curso'),
        ),
    ]
