# Generated by Django 4.0 on 2022-04-19 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalog_location_alter_course_level_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_level',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course', verbose_name='Curso'),
        ),
    ]
