# Generated by Django 4.0 on 2022-05-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0080_alter_location_created_at_alter_pool_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_lane', models.IntegerField(default=10, verbose_name='Capacidad por carril')),
                ('begin_validity', models.DateField(verbose_name='Inicio Validez')),
                ('end_validity', models.DateField(verbose_name='Fin Validez')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Sede')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.pool', verbose_name='Piscina')),
            ],
            options={
                'verbose_name': 'Aforo por Piscina',
                'verbose_name_plural': 'Aforo por Piscina',
            },
        ),
    ]
