# Generated by Django 4.0 on 2022-04-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicaluser_avatar_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='doc_num',
            field=models.CharField(db_index=True, default=-5, max_length=10, verbose_name='N° Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='doc_num',
            field=models.CharField(default=-5, max_length=10, unique=True, verbose_name='N° Documento'),
            preserve_default=False,
        ),
    ]
