# Generated by Django 4.0 on 2022-04-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_historicaluser_doc_num_remove_user_doc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='doc_num',
            field=models.CharField(max_length=10, null=True, verbose_name='N° Documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='doc_num',
            field=models.CharField(max_length=10, null=True, verbose_name='N° Documento'),
        ),
    ]
