# Generated by Django 4.0 on 2022-04-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_historicaluser_doc_num_user_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='doc_num',
            field=models.CharField(db_index=True, max_length=10, verbose_name='N° Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='doc_num',
            field=models.CharField(max_length=10, unique=True, verbose_name='N° Documento'),
        ),
    ]
