# Generated by Django 4.0 on 2022-04-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_historicaluser_doc_num_alter_user_doc_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
