# Generated by Django 4.0 on 2021-12-08 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Sede')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre Sede')),
                ('address', models.CharField(max_length=255, verbose_name='Direccion')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('id_region', models.CharField(max_length=5, verbose_name='Id Region')),
                ('region', models.CharField(max_length=50, verbose_name='Nombre Region')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 8, 17, 26, 21, 676826))),
                ('updated_at', models.DateTimeField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created_by', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Piscina')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('lanes', models.IntegerField(default=10, verbose_name='Cantidad Carriles')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ancho (mt)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largo (mt)')),
                ('min_depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Profundidad mínima (mt)')),
                ('max_depth', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Profundidad máxima (mt)')),
                ('is_available', models.BooleanField(default=False, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 8, 17, 26, 21, 677563))),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lane_created_by', to='users.user')),
                ('id_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='locations.location', verbose_name='Sedes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lane_updated_by', to='users.user')),
            ],
            options={
                'verbose_name': 'Piscina',
                'verbose_name_plural': 'Piscinas',
            },
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Carril')),
                ('lane_no', models.IntegerField(verbose_name='N° Carril')),
                ('id_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.pool', verbose_name='Piscina')),
            ],
            options={
                'verbose_name': 'Carril',
                'verbose_name_plural': 'Carriles',
            },
        ),
    ]
