# Generated by Django 4.0 on 2022-03-27 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_location_created_at_alter_pool_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='id_city',
            field=models.CharField(blank=True, max_length=5, verbose_name='Id Ciudad'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='locations', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 17, 20, 3, 555596)),
        ),
        migrations.AlterField(
            model_name='location',
            name='id_region',
            field=models.CharField(max_length=2, verbose_name='Id Region'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 17, 20, 3, 555596)),
        ),
    ]
