# Generated by Django 4.0 on 2022-03-29 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_alter_location_created_at_alter_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 25, 35, 608675)),
        ),
        migrations.AlterField(
            model_name='pool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 25, 35, 609675)),
        ),
    ]
