# Generated by Django 4.0 on 2022-03-29 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicaluser_avatar_user_avatar'),
        ('locations', '0010_location_state_alter_location_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_by', to='users.user'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 28, 47, 669816)),
        ),
        migrations.AlterField(
            model_name='pool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 10, 28, 47, 670815)),
        ),
    ]
