# Generated by Django 4.0 on 2022-04-17 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0056_alter_location_created_at_alter_pool_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='id_location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 16, 15, 33, 339045)),
        ),
        migrations.AlterField(
            model_name='pool',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 16, 15, 33, 339766)),
        ),
    ]
