# Generated by Django 4.0 on 2022-04-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0047_alter_location_created_at_alter_pool_created_at'),
        ('schedule', '0008_alter_schedule_day_daytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2022, verbose_name='Año')),
                ('month', models.IntegerField(default=4, verbose_name='Mes')),
                ('day', models.IntegerField(default=15, verbose_name='Día')),
                ('day_week', models.IntegerField(default=5, verbose_name='Día de la semana')),
                ('day_label', models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=(6, 'Sábado'), max_length=10, verbose_name='Día de la semana')),
                ('holiday', models.BooleanField(blank=True, default=False, null=True, verbose_name='Feriado')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Calendario',
                'verbose_name_plural': 'Calendarios',
            },
        ),
    ]
