# Generated by Django 4.0 on 2022-04-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0048_alter_location_created_at_alter_pool_created_at'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='month_label',
            field=models.CharField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=(5, 'Mayo'), max_length=10, verbose_name='Nombre mes'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='day_label',
            field=models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=(5, 'Viernes'), max_length=10, verbose_name='Nombre día'),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('location', 'year', 'month', 'day')},
        ),
    ]
