# Generated by Django 4.0 on 2022-04-16 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_calendar_unique_together_calendar_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='daytype',
            field=models.CharField(choices=[('WD', 'Lunes a Viernes'), ('SA', 'Sábado'), ('SU', 'Domingo'), ('HO', 'Festivo')], default='WD', max_length=2),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 15, 22, 10, 33, 884921), verbose_name='Fecha'),
        ),
    ]
