# Generated by Django 4.0 on 2022-04-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_calendar_date_alter_calendar_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
