# Generated by Django 4.0 on 2022-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_alter_calendar_day_alter_calendar_day_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='day',
            field=models.IntegerField(default=19, verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month',
            field=models.IntegerField(default=5, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='month_label',
            field=models.CharField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=(5, 'Mayo'), max_length=10, verbose_name='Nombre mes'),
        ),
    ]
