# Generated by Django 4.0 on 2021-12-08 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Miembro')),
                ('doc_num', models.CharField(max_length=10, unique=True, verbose_name='N° Documento')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sex', models.CharField(max_length=1, verbose_name='Sexo')),
                ('status', models.CharField(choices=[('PE', 'Pendiente'), ('AC', 'Activo'), ('IN', 'Inactivo')], default='PE', max_length=2, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 12, 8, 17, 26, 21, 682232))),
                ('updated_at', models.DateTimeField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_created_by', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_updated_by', to='users.user')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
    ]
