# Generated by Django 4.0 on 2021-12-08 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 18, 49, 50, 895889)),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
