# Generated by Django 4.0 on 2022-04-07 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_historicaluser_doc_num_alter_user_doc_num'),
        ('members', '0028_alter_member_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_canceled_by', to='users.user'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 12, 47, 19, 256269)),
        ),
    ]
