# Generated by Django 4.0 on 2022-04-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_alter_catalog_location'),
        ('planning', '0011_alter_calendar_day_alter_calendar_day_label_and_more'),
        ('locations', '0070_alter_location_created_at_alter_pool_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAsigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sessions', models.IntegerField(verbose_name='Cantidad de sesiones')),
                ('teacher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profesor')),
                ('startdate', models.DateField(verbose_name='Inicio')),
                ('enddate', models.DateField(verbose_name='Fin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.course', verbose_name='Curso')),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.lane')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.course_level', verbose_name='Nivel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.location', verbose_name='Sede')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.pool', verbose_name='Píscina')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(verbose_name='Hora inicio')),
                ('endtime', models.TimeField(verbose_name='Hora inicio')),
                ('course_asigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseasigned')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.calendar', verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(verbose_name='Día de la semana')),
                ('starttime', models.TimeField(verbose_name='Hora inicio')),
                ('endtime', models.TimeField(verbose_name='Hora inicio')),
                ('course_asigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseasigned')),
            ],
            options={
                'verbose_name': 'Horario Curso',
                'verbose_name_plural': 'Horarios Cursos',
            },
        ),
    ]
