# Generated by Django 4.0 on 2022-04-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_courseasigned_courseassigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='course_asigned',
            new_name='course_assigned',
        ),
    ]
