# Generated by Django 4.0 on 2022-04-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_alter_calendar_day_alter_calendar_day_label_and_more'),
        ('schedule', '0008_alter_schedule_day_daytype'),
        ('courses', '0003_rename_course_asigned_courseschedule_course_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='coursesession',
            name='starttime',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.schedule_slot', verbose_name='Bloque horario (plan)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesession',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='planning.slot', verbose_name='Bloque horario'),
            preserve_default=False,
        ),
    ]
