# Generated by Django 4.0 on 2022-04-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_course_asigned_coursesession_course_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesession',
            name='course_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.courseschedule'),
            preserve_default=False,
        ),
    ]
