# Generated by Django 4.0 on 2022-04-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursesession_course_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassigned',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name='Fin'),
        ),
    ]
