# Generated by Django 4.0 on 2022-04-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0032_alter_location_created_at_alter_pool_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Id Horario')),
                ('begin_validity', models.DateField(verbose_name='Inicio de vigencia')),
                ('end_validity', models.DateField(verbose_name='Fin vigencia')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Schedule_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytype', models.CharField(choices=[('WE', 'Dia Laboral'), ('SA', 'Sábado'), ('SU', 'Domingo'), ('HO', 'Festivo')], default='WE', max_length=2, verbose_name='Tipo de Día')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule', verbose_name='Id Horario')),
            ],
            options={
                'verbose_name': 'Día horario',
                'verbose_name_plural': 'Días horario',
                'unique_together': {('schedule', 'daytype')},
            },
        ),
        migrations.CreateModel(
            name='Schedule_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(verbose_name='Slot')),
                ('starttime', models.TimeField(verbose_name='Hora Inicio')),
                ('endtime', models.TimeField(verbose_name='Hora Fin')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule_day', verbose_name='Día')),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horario',
                'unique_together': {('schedule_day', 'slot')},
            },
        ),
    ]
