# Generated by Django 4.0 on 2022-04-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytype', models.CharField(choices=[('WE', 'Dia Laboral'), ('SA', 'Sábado'), ('SU', 'Domingo'), ('HO', 'Festivo')], default='WE', max_length=2, verbose_name='Tipo de Día')),
            ],
            options={
                'verbose_name': 'Día horario',
                'verbose_name_plural': 'Días horario',
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('slot', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Slot')),
                ('starttime', models.TimeField(verbose_name='Hora Inicio')),
                ('endtime', models.TimeField(verbose_name='Hora Fin')),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horario',
            },
        ),
        migrations.AlterUniqueTogether(
            name='schedule_slot',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedule_slot',
            name='schedule_day',
        ),
        migrations.DeleteModel(
            name='Schedule_Day',
        ),
        migrations.DeleteModel(
            name='Schedule_Slot',
        ),
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.ManyToManyField(to='schedule.DayType'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='slots',
            field=models.ManyToManyField(to='schedule.Slots'),
        ),
    ]
