# Generated by Django 4.0 on 2022-04-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_daytype_slots_alter_schedule_slot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='slots',
        ),
        migrations.AddField(
            model_name='daytype',
            name='slots',
            field=models.ManyToManyField(to='schedule.Slots'),
        ),
    ]
