# Generated by Django 4.0 on 2022-04-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_slots_daytype_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytype',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='daytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.daytype'),
            preserve_default=False,
        ),
    ]
