# Generated by Django 4.0 on 2022-04-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_daytype_slots_remove_schedule_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytype', models.CharField(choices=[('WE', 'Dia Laboral'), ('SA', 'Sábado'), ('SU', 'Domingo'), ('HO', 'Festivo')], default='WE', max_length=2, verbose_name='Tipo de Día')),
            ],
            options={
                'verbose_name': 'Día horario',
                'verbose_name_plural': 'Días horario',
            },
        ),
        migrations.CreateModel(
            name='Schedule_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(verbose_name='Slot')),
                ('starttime', models.TimeField(verbose_name='Hora Inicio')),
                ('endtime', models.TimeField(verbose_name='Hora Fin')),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule_day', verbose_name='Día')),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horario',
                'unique_together': {('schedule_day', 'slot')},
            },
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='daytype',
        ),
        migrations.DeleteModel(
            name='DayType',
        ),
        migrations.AddField(
            model_name='schedule_day',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule', verbose_name='Id Horario'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule_day',
            unique_together={('schedule', 'daytype')},
        ),
    ]
