# Generated by Django 4.0 on 2022-04-12 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_day_schedule_slot_delete_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule_slot',
            options={'ordering': ['slot'], 'verbose_name': 'Bloque horario', 'verbose_name_plural': 'Bloques horario'},
        ),
        migrations.AddField(
            model_name='schedule_day',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='¿Está abierto?'),
        ),
        migrations.AlterField(
            model_name='schedule_day',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_type', to='schedule.schedule', verbose_name='Id Horario'),
        ),
        migrations.AlterField(
            model_name='schedule_slot',
            name='schedule_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='schedule.schedule_day', verbose_name='Día'),
        ),
    ]
