# Generated by Django 4.0 on 2022-04-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_schedule_slot_options_schedule_day_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_day',
            name='daytype',
            field=models.CharField(choices=[('WD', 'Dia Laboral'), ('SA', 'Sábado'), ('SU', 'Domingo'), ('HO', 'Festivo')], default='WD', max_length=2, verbose_name='Tipo de Día'),
        ),
    ]
