# Generated by Django 4.0 on 2022-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedule_day_daytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_day',
            name='daytype',
            field=models.CharField(choices=[('WD', 'Lunes a Viernes'), ('SA', 'Sábado'), ('SU', 'Domingo'), ('HO', 'Festivo')], default='WD', max_length=2, verbose_name='Tipo de Día'),
        ),
    ]
